# Generated by Django 4.2 on 2025-01-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_alter_events_desc_alter_events_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
