# Generated by Django 4.2 on 2025-02-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0004_alter_events_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.IntegerField(choices=[(0, 'Birthday'), (1, 'DA / Quiz'), (2, 'Others')], default=2),
        ),
    ]
