# Generated by Django 4.2 on 2025-02-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0006_category_alter_events_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
