# Generated by Django 4.2 on 2025-02-03 12:04

from django.db import migrations, models
import django.db.models.deletion
import mycalendar.models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0008_category_events_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.ForeignKey(default=mycalendar.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='mycalendar.category'),
        ),
    ]
