# Generated by Django 4.2 on 2025-02-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0010_alter_events_event_date_fcmtokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCMTokens',
        ),
    ]
