# Generated by Django 4.2 on 2025-02-04 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0009_alter_events_category'),
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycalendar.events')),
            ],
        ),
    ]
